### ISSUE TITLE
Fix 'ReduceLROnPlateau' has no attribute 'get_last_lr'

### ISSUE THREAD

**Issue by irg1008** [TorchEnsemble-Community/Ensemble-Pytorch#109]
This scheduler doesn't have this attributte because it doesn't inherit from `_LRScheduler`, and simply implementes the generic 'object' class.

Instead of getting the leanring rate with `get_last_lr`, we could fetch it with `optimizer.param_groups[0]['lr']` for this very specific case.

**Comment by xuyxu** [comment]
Hi @irg1008, thanks for your kind reminder, will appreciate a PR very much ;-)

**Comment by SarthakJariwala** [comment]
Hi @xuyxu, if you are still looking for a PR, I would be happy to work on it

**Comment by xuyxu** [comment]
Great! Feel free to work on it, and let me know if you need any help ;-) @SarthakJariwala

**Comment by SarthakJariwala** [comment]
Hi @xuyxu - see PR #128 :-)
