### ISSUE TITLE
How to ensemble several different classification models into a voter?

### ISSUE THREAD

**Issue by jisutich** [TorchEnsemble-Community/Ensemble-Pytorch#117]
Hi,

I just start learning neural network and I want to create a voter for several different classification models trained on some dataset. It seems that this package is what I need. And I find the sample code in the document [https://ensemble-pytorch.readthedocs.io/en/latest/index.html](url). 

`
model = VotingClassifier(
    estimator=MLP,
    n_estimators=10,
    cuda=True,
)
`
My naive understanding is that here we have 10 same estimators. Can we transfer a list of models instead of just `MLP` into the arguments?

Thanks

**Comment by xuyxu** [comment]
Hi @jisutich, please refer to #49 for details on why heteregenous ensemble is hard to implement, thanks.

**Comment by jisutich** [comment]
OK I got it. Thanks.
