### ISSUE TITLE
Regarding the latest code in pip

### ISSUE THREAD

**Issue by singhabhinav** [TorchEnsemble-Community/Ensemble-Pytorch#139]
Hello,

Is there any plan to update the latest code in pip?

I could see that in one of the pull request hard voting was implemented. But it is not available in the pip version.

**Comment by xuyxu** [comment]
Hi @singhabhinav, sorry for the late response. You could install the package from source using the master branch.
* Clone this repo to your local disk
* Open a terminal, and switch into the target directory
* Run `python setup.py install`
