### ISSUE TITLE
Patience is ignored in bagging models

### ISSUE THREAD

**Issue by lorenzozanisi** [TorchEnsemble-Community/Ensemble-Pytorch#141]
I was having a look at bagging models in `bagging.py`. Specifically, at [this line](https://github.com/TorchEnsemble-Community/Ensemble-Pytorch/blob/317e2e5eb6008fbd424860eb78769d7bc1ef8c79/torchensemble/bagging.py#L274) it looks like the ensemble state at the end of the training is saved, thus overwriting the decisions made in the validation loop. Can someone confirm if I'm reading this correctly?

**Comment by xuyxu** [comment]
Hi @lorenzozanisi, you are right, the strategy of saving the model with the best validation performance will not have a real effect. Thanks for reporting, will fix it soon.

**Comment by xuyxu** [comment]
@all-contributors please add @lorenzozanisi for bug

**Comment by lorenzozanisi** [comment]
Great, thanks for the fix!
