### ISSUE TITLE
Getting error while using GradientBoostingClassifier

### ISSUE THREAD

**Issue by singhabhinav** [TorchEnsemble-Community/Ensemble-Pytorch#146]
Hi,

I am getting below error while using GradientBoostingClassifier. Could you please let me know how can we fix this
![Screenshot 2023-03-01 at 3 33 44 PM](https://user-images.githubusercontent.com/10808722/222171423-b6c92a1a-954e-40cd-8312-bef510c23630.png)

**Comment by xuyxu** [comment]
Hi @singhabhinav, what is the number of classes in your data loader, and what is the network structure of your base estimator ?

**Comment by singhabhinav** [comment]
Hi @xuyxu 

I have 60 classes in my output and please find the attached network structure 
![Screenshot 2023-03-04 at 2 50 43 PM](https://user-images.githubusercontent.com/10808722/222906167-ddd42a8f-ef30-4e5d-a59b-c0af22df999d.png)

**Comment by xuyxu** [comment]
Thanks @singhabhinav, another thing to confirm is that the data batch fed to `CIF` is of the shape `(batch_size, 10)`, right?

**Comment by singhabhinav** [comment]
@xuyxu yes I can confirm this.

Same code is working fine with VotingClassifier but throws the above error with GradientBoostingClassifier. I have printed the shape of input tensor and it is indeed (batch_size, 10)

![Screenshot 2023-03-05 at 1 18 12 PM](https://user-images.githubusercontent.com/10808722/222960023-5093ff11-1dce-44c2-a705-5a87da8a1906.png)
