### ISSUE TITLE
model.predict not working with test_loader as in the documentation

### ISSUE THREAD

**Issue by francescamanni1989** [TorchEnsemble-Community/Ensemble-Pytorch#89]
Hi! Thanks for your amazing work with torch_ensemble. 
I am trying to use model_predict for the MNIST example by implementing the following as in the documentation.
model.predict(test_loader).

However I keep having this error.
ValueError: The type of input X should be one of {{torch.Tensor, np.ndarray}}.

**Comment by xuyxu** [comment]
Hi @francescamanni1989, if you want to evaluate the test_loader, please use the `evaluate` method.

**Comment by xuyxu** [comment]
closed due to inactivity
