### ISSUE TITLE
typo in readthedocs

### ISSUE THREAD

**Issue by kiranchari** [TorchEnsemble-Community/Ensemble-Pytorch#91]
In https://ensemble-pytorch.readthedocs.io/en/stable/quick_start.html#set-the-logger

`from torchensemble.utils import set_logger` 
must be changed to
`from torchensemble.utils.logging import set_logger`

The former throws an import error

**Comment by xuyxu** [comment]
Thanks, will appreciate a PR very much ;-)

**Comment by xuyxu** [comment]
@all-contributors please add @kiranchari for doc
