### ISSUE TITLE
Can you share the original source of fusion? I would appreciate it!

### ISSUE THREAD

**Issue by Sobbbbbber** [TorchEnsemble-Community/Ensemble-Pytorch#99]
RT

**Comment by xuyxu** [comment]
Hi @Sobbbbbber, `fusion` is arguably the most direct way of improving the model capacity of a base estimator that comes into people's mind, I dont think there is any paper that claims `fusion` as an  ensemble method ;-)

**Comment by Sobbbbbber** [comment]
OK, thanks for your reply @xuyxu :-）
It's a great work~
